# Generated by Django 3.2.5 on 2021-08-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='jane', max_length=10)),
                ('last_name', models.CharField(default='Sincere', max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('image', models.ImageField(default='.jpeg', upload_to='images')),
                ('email', models.EmailField(default='estherayebaza@gmail.com', max_length=254)),
                ('cv', models.FileField(default='cv.png', upload_to='images')),
                ('courses_taught', models.CharField(default='python', max_length=30)),
                ('trainer_Id', models.CharField(default='2376889999', max_length=20)),
                ('lessons_attended', models.PositiveSmallIntegerField(default='4')),
                ('bank_account', models.CharField(default='34526677789', max_length=30)),
                ('contract', models.CharField(default='seven_month', max_length=30)),
                ('profession', models.CharField(default='backend_developer', max_length=20)),
            ],
        ),
    ]
