# Generated by Django 3.2.5 on 2021-10-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank='true', max_length=10, null='true')),
                ('last_name', models.TextField(blank='true', max_length=10, null='true')),
                ('gender', models.TextField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('image', models.ImageField(blank='true', null='true', upload_to='images')),
                ('email', models.EmailField(blank='true', max_length=254, null='true')),
                ('cv', models.FileField(blank='true', null='true', upload_to='images')),
                ('courses_taught', models.TextField(blank='true', max_length=30, null='true')),
                ('trainer_Id', models.TextField(blank='true', max_length=20, null='true')),
                ('lessons_attended', models.PositiveSmallIntegerField(blank='true', null='true')),
                ('bank_account', models.TextField(blank='true', max_length=30, null='true')),
                ('contract', models.TextField(blank='true', max_length=30, null='true')),
                ('profession', models.TextField(blank='true', max_length=200, null='true')),
            ],
        ),
    ]
