# Generated by Django 3.2.5 on 2021-08-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='profession',
            field=models.CharField(default='backend_developer', max_length=200),
        ),
    ]
