# Generated by Django 3.2.5 on 2021-10-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_auto_20210917_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='bank_account',
            field=models.TextField(blank='true', max_length=30, null='true'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='contract',
            field=models.TextField(blank='true', max_length=30, null='true'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='courses_taught',
            field=models.TextField(blank='true', max_length=30, null='true'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='first_name',
            field=models.TextField(blank='true', max_length=10, null='true'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='gender',
            field=models.TextField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='last_name',
            field=models.TextField(blank='true', max_length=10, null='true'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profession',
            field=models.TextField(blank='true', max_length=200, null='true'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='trainer_Id',
            field=models.TextField(blank='true', max_length=20, null='true'),
        ),
    ]
