# Generated by Django 3.2.5 on 2021-09-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventscalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(blank='true', max_length=20, null='true'),
            preserve_default='true',
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
