# Generated by Django 3.2.5 on 2021-10-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.TextField(blank='true', max_length=30, null='true')),
                ('syllabus', models.TextField(blank='true', max_length=100, null='true')),
                ('course_code', models.TextField(max_length=10)),
                ('course_description', models.TextField(max_length=200)),
                ('course_material', models.TextField(max_length=400)),
                ('course_duration', models.TextField(max_length=20)),
                ('course_units', models.TextField(max_length=100)),
            ],
        ),
    ]
