# Generated by Django 3.2.5 on 2021-08-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='jane', max_length=10)),
                ('syllabus', models.CharField(default='Sincere', max_length=10)),
                ('course_code', models.CharField(max_length=10)),
                ('course_description', models.CharField(max_length=200)),
                ('course_material', models.CharField(max_length=400)),
                ('course_duration', models.CharField(max_length=20)),
                ('course_units', models.CharField(max_length=50)),
            ],
        ),
    ]
