# Generated by Django 3.2.5 on 2021-10-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210917_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_code',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_duration',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_material',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.TextField(blank='true', max_length=30, null='true'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_units',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='syllabus',
            field=models.TextField(blank='true', max_length=100, null='true'),
        ),
    ]
