# Generated by Django 3.2.5 on 2021-10-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank='true', max_length=18, null='true')),
                ('last_name', models.TextField(blank='true', max_length=18, null='true')),
                ('age', models.PositiveSmallIntegerField(blank='true', null='true')),
                ('date_of_birth', models.DateField(blank='True', null='True')),
                ('gender', models.TextField(blank='True', choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null='True')),
                ('mentor', models.TextField(blank='True', max_length=29, null='True')),
                ('medical_form', models.FileField(blank='True', null='True', upload_to='images')),
                ('id_number', models.TextField(blank='True', max_length=20, null='True')),
                ('passport_number', models.TextField(blank='True', max_length=20, null='True')),
                ('image', models.ImageField(blank='true', null='true', upload_to='images')),
                ('nationality', models.TextField(blank='True', max_length=15, null='True')),
                ('class_name', models.TextField(blank='True', max_length=10, null='True')),
                ('room_number', models.TextField(blank='True', max_length=5, null='True')),
                ('email', models.EmailField(blank='True', max_length=254, null='True')),
                ('county_or_district', models.TextField(blank='True', max_length=15, null='True')),
                ('big_sister', models.TextField(blank='True', max_length=20, null='True')),
            ],
        ),
    ]
