# Generated by Django 3.2.4 on 2021-07-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='big_sister',
            field=models.CharField(default='BigSister', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='class_name',
            field=models.CharField(default='Anitahb', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='county_or_district',
            field=models.CharField(default='Kanungu', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=10, max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='id_number',
            field=models.CharField(default='1234556256AD', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='.jpeg', upload_to='images'),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_form',
            field=models.FileField(default='.png', upload_to='images'),
        ),
        migrations.AddField(
            model_name='student',
            name='mentor',
            field=models.CharField(default='phionah', max_length=29),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='Uganda', max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_number',
            field=models.CharField(default=2100876, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='room_number',
            field=models.CharField(default=12, max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(default=32),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default='sept'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='jane', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Sincere', max_length=10),
        ),
    ]
