# Generated by Django 3.2.5 on 2021-10-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.TextField(blank='True', choices=[('M', 'Male'), ('F', 'Female')], null='True'),
        ),
    ]
