# Generated by Django 3.2.5 on 2021-10-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='big_sister',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='county_or_district',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, default='anyijukirjanett@gmail.com', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.TextField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex/Parody')], default='female', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.TextField(blank=True, default=5343, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='medical_form',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='mentor',
            field=models.TextField(blank=True, max_length=29, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.TextField(blank=True, default='Ugandan', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_number',
            field=models.TextField(blank=True, default=3445, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='room_number',
            field=models.TextField(blank=True, max_length=5, null=True),
        ),
    ]
