# Generated by Django 3.2.5 on 2021-08-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210813_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='ayebaza', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='Esther', max_length=10),
        ),
    ]
