# Generated by Django 3.2.5 on 2021-09-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20210827_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='.jpeg', upload_to='images'),
        ),
    ]
