# Generated by Django 3.2.5 on 2021-09-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_student_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank='true', null='true', upload_to='images'),
        ),
    ]
