# Generated by Django 3.2.5 on 2021-10-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='big_sister',
            field=models.TextField(blank='True', max_length=20, null='True'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.TextField(blank='True', max_length=10, null='True'),
        ),
        migrations.AlterField(
            model_name='student',
            name='county_or_district',
            field=models.TextField(blank='True', max_length=15, null='True'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.TextField(blank='true', max_length=18, null='true'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.TextField(blank='True', choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null='True'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.TextField(blank='True', max_length=20, null='True'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.TextField(blank='true', max_length=18, null='true'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mentor',
            field=models.TextField(blank='True', max_length=29, null='True'),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.TextField(blank='True', max_length=15, null='True'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_number',
            field=models.TextField(blank='True', max_length=20, null='True'),
        ),
        migrations.AlterField(
            model_name='student',
            name='room_number',
            field=models.TextField(blank='True', max_length=5, null='True'),
        ),
    ]
